# Generated by Django 6.0.2 on 2026-03-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_adv'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv',
            name='name',
            field=models.CharField(default='Company Name', max_length=255, verbose_name='Company name'),
        ),
    ]
